name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installQt
      run: sudo apt install qt5-default --fix-missing
    - name: mkdir_build
      run: mkdir build
    - name: cd_build
      run: qmake ..
    - name: make
      run: make
#     - name: make distcheck
#       run: make distcheck
